name: VanishNoPacket
main: org.kitteh.vanish.VanishPlugin
version: 3.4
website: http://kitteh.org
softdepend: [Essentials,dynmap,JSONAPI,bPermissions,Spout]
author: mbaxter
description: Vanish for the distinguished admin
dev-url: http://dev.bukkit.org/server-mods/vanish/
commands:
  vanish:
    description: poof
    usage: /vanish
    aliases: [v,np,nf,ni,nc]
permissions:
  vanish.currentlyVanished:
    default: false
    description: Do not manually play with this. Do not.
  vanish.vanish:
    default: op
    description: |
      Allows player to vanish. 
      REALLY should give players with this access to vanish.see
  vanish.see:
    default: op
    description: Allows player to see vanished players
  vanish.statusupdates:
    default: op
    description: Informed about players changing status
  vanish.list:
    default: op
    description: Acquire a list of vanished users
  vanish.nopickup:
    default: false
    description: If true player can pick up items when vanished
  vanish.nofollow:
    default: false
    description: If true mobs do not follow player when vanished
  vanish.notrample:
    default: false
    description: If true player does not trample crops
  vanish.nointeract:
    default: false
    description: If true player cannot press buttons, break or place blocks, open doors, activate pressure pads etc
  vanish.nochat:
    default: false
    description: No chatting while vanished
  vanish.preventincomingdamage:
    default: false
    description: Prevent being harmed by things around you while vanished
  vanish.preventoutgoingdamage:
    default: false
    description: Prevent accidentally hurting stuff while vanished
  vanish.preventdamage:
    default: false
    description: Prevent damage both ways
    children:
      vanish.preventoutgoingdamage: true
      vanish.preventincomingdamage: true
  vanish.joinwithoutannounce:
    default: false
    description: Join without announcing it
  vanish.joinvanished:
    default: false
    description: Join vanished
  vanish.silentjoin:
    default: false
    description: Join silently. Announce on toggling vanish off
    children:
      vanish.joinwithoutannounce: true
      vanish.joinvanished: true
  vanish.silentquit:
    default: false
    description: ALWAYS quit silently. 
  vanish.toggle.see:
    default: false
    description: Toggle seeing other vanished players
  vanish.toggle.nopickup:
    default: false
    description: Toggle pickup ability
  vanish.toggle.nofollow:
    default: false
    description: Toggle mob aggro
  vanish.toggle.nointeract:
    default: false
    description: Toggle interaction ability (doors, pressurepads, buttons, breaking or placing blocks, etc)
  vanish.toggle.nochat:
    default: false
    description: Toggle ability to chat
  vanish.toggle.damageout:
    default: false
    description: Toggle outgoing damage
  vanish.toggle.damagein:
    default: false
    description: Toggle incoming damage
  vanish.toggle.damage:
    default: false
    description: Toggle both damage in and out
    children:
      vanish.toggle.damageout: true
      vanish.toggle.damagein: true
  vanish.toggle.all:
    default: false
    description: Allows user to toggle all their settings ingame
    children:
      vanish.toggle.see: true
      vanish.toggle.nopickup: true
      vanish.toggle.nofollow: true
      vanish.toggle.damage: true
      vanish.toggle.nointeract: true
      vanish.toggle.nochat: true
  vanish.fakeannounce:
    default: false
    description: Fake joining/leaving
  vanish.adminalerts:
    default: op
    description: Receive alerts about updates and such
  vanish.permtest.self:
    default: true
    description: If PermTest is enabled, be able to use it on yourself
  vanish.permtest.other:
    default: op
    description: If PermTest is enabled, be able to use it on others
  vanish.permtest.all:
    default: op
    description: If PermTest is enabled, be able to use on self and others
    children:
      vanish.permtest.self: true
      vanish.permtest.other: true
  vanish.hooks.dynmap.alwayshidden:
    default: false
    description: Always hide from dynmap
  vanish.hooks.essentials.hide:
    default: false
    description: Hide user in Essentials
  vanish.spout.status:
    default: false
    description: See a status bar if vanished in spoutcraft
  vanish.reload:
    default: op
    description: Reloads some VNP systems
  vanish.standard:
    default: false
    description: Can vanish, see vanished, no pickup when vanished
    children:
      vanish.see: true
      vanish.vanish: true
      vanish.list: true
      vanish.nopickup: true
      vanish.nofollow: true
      vanish.notrample: true
      vanish.nointeract: true
      vanish.fakeannounce: true
      vanish.preventdamage: true
      vanish.statusupdates: true
      vanish.adminalerts: true
  vanish.*:
    default: false    
    description: Oh god everything.
    children:
      vanish.standard: true
      vanish.nochat: true
      vanish.silentjoin: true
      vanish.silentquit: true
      vanish.toggle.all: true
      vanish.hooks.dynmap.alwayshidden: true
      vanish.hooks.essentials.hide: true
      vanish.permtest.all: true
      vanish.spout.status: true
      vanish.reload: true
